#!/usr/bin/perl -w
#
# Copyright (c) 2008-2009 - DRS CenGen, LLC, Columbia, Maryland
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# * Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in
#   the documentation and/or other materials provided with the
#   distribution.
# * Neither the name of DRS CenGen, LLC nor the names of its
#   contributors may be used to endorse or promote products derived
#   from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# The copyright holder hereby grants to the U.S. Government a copyright
# license to use this computer software/computer software documentation
# that is of the same scope as the rights set forth in the definition of
# "unlimited rights" found in DFARS 252.227-7014(a)(15)(June 1995).
#

use Socket;
use Getopt::Long;
use strict;

my $help;
my $nem;

&usage and exit 1 unless 
  GetOptions(
             'help'         =>\$help,
             'nem=i'        =>\$nem,
            );

&usage and exit 0 if $help;

&usage and exit 1 if scalar(@ARGV) != 2;

socket(SOCKET, PF_INET, SOCK_DGRAM, getprotobyname("udp"))
  or die "socket: $!";

my $hostaddr =  gethostbyname($ARGV[0]);

my $addr = sockaddr_in(45701,$hostaddr);

my $msg;

if($nem)
{
  $msg = pack("nnnn",2,4,$nem,$ARGV[1]);
}
else
{
  $msg = pack("nnn",1,2,$ARGV[1]);
}

send(SOCKET,$msg,0,$addr) or
  die "send $!";

exit 0;

sub usage
{
  print "\n";
  print "usage: emaneloglevel [OPTIONS]... EMANEADDR LEVEL\n";
  print "\n";
  print "options:\n";
  print "    --help             Print this message and exit\n";
  print "    --nem NEM          NEM Id for a targeted level change\n";
  print "\n";
}
